time-capsuleリポジトリからAWSへOIDC認証でデプロイを可能にする (#764)
* カスタムワードを追加します。

* pre-commit.ymlを更新し、terraform関連ファイルを追加しました。

* 更新ラベラーアクションのバージョンをv5に変更

* 更新自動アサインアクションのバージョン。

* .asdfrc に legacy_version_file = yes を追加する

* 新しいTerraformバージョンを追加します。

* ラベラーの設定を更新します。

* Update terraform workflow for AWS management, portfolio, and sandbox. (50 characters)

* Terraformワークフローのブランチ設定を更新

* time_capsule を追加する。

* terraform-docs: automated action

* 不要なジョブ名を削除します。

* アップデートシェルチェック v0.9.0 から v0.10.0 に変更

* ワークフローの成功と失敗を処理するステップを追加

* バージョンを1.6.6から1.7.5に更新する。

* バージョンを1.7.5に更新する。

* tfstateファイルのキーを更新する

---------

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

diff --git a/.github/workflows/_terraform-aws-management.yml b/.github/workflows/_terraform-aws-management.yml
--- a/.github/workflows/_terraform-aws-management.yml
+++ b/.github/workflows/_terraform-aws-management.yml
@@ -3,25 +3,9 @@ name: Terraform - AWS - Management
 
 on:
   pull_request:
-    branches:
-      - main
-    paths:
-      - ".github/actions/**/action.yml"
-      - ".github/workflows/_terraform-aws-management.yml"
-      - ".tool-versions"
-      - "terraform/environments/management/**"
-      - "terraform/modules/**"
-      - "terraform/usecases/**"
   push:
     branches:
       - main
-    paths:
-      - ".github/actions/**/action.yml"
-      - ".github/workflows/_terraform-aws-management.yml"
-      - ".tool-versions"
-      - "terraform/environments/management/**"
-      - "terraform/modules/**"
-      - "terraform/usecases/**"
   workflow_call:
     inputs:
       CHECK_DIFF:
@@ -39,14 +23,8 @@ on:
           - "_true"
           - "_false"
 
-permissions:
-  contents: read
-  deployments: write
-  id-token: write
-  pull-requests: write
-
 concurrency:
-  group: terraform-aws-management
+  group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 
 env:
@@ -57,37 +35,34 @@ env:
 
 jobs:
   set-matrix:
-    name: Set Matrix
     runs-on: ubuntu-latest
     timeout-minutes: 5
     outputs:
       matrix: ${{ steps.set-matrix.outputs.matrix }}
     steps:
-      - name: Checkout source code
-        uses: actions/checkout@v4
-
-      - name: Set Matrix
+      - uses: actions/checkout@v4
+      - uses: ./.github/actions/set-matrix
         id: set-matrix
-        uses: ./.github/actions/set-matrix
         with:
           AWS_ENV_NAME: ${{ env.AWS_ENV_NAME }}
 
-  terraform:
-    name: Terraform - AWS - Management A
+  terraform-aws-management:
     needs: [set-matrix]
     if: ${{ needs.set-matrix.outputs.matrix != '["_empty"]' }}
     runs-on: ubuntu-latest
+    permissions:
+      id-token: write # For aws-actions/configure-aws-credentials
+      contents: read # For aws-actions/configure-aws-credentials
+      deployments: write # For bobheadxi/deployments
+      pull-requests: write # For bobheadxi/deployments
     timeout-minutes: 15
     strategy:
       fail-fast: false
       matrix:
         directory: ${{ fromJson(needs.set-matrix.outputs.matrix )}}
     steps:
-      - name: Checkout source code
-        uses: actions/checkout@v4
-
-      - name: AWS Credential
-        uses: ./.github/actions/aws-credential
+      - uses: actions/checkout@v4
+      - uses: ./.github/actions/aws-credential
         with:
           oidc-iam-role: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.OIDC_IAM_ROLE }}
 
@@ -126,16 +101,13 @@ jobs:
           env: ${{ steps.deployment.outputs.env }}
           deployment_id: ${{ steps.deployment.outputs.deployment_id }}
 
-  delete_pr_comments:
-    name: Delete PR Comments
-    needs: [terraform]
+  delete-pr-comments:
+    needs: [terraform-aws-management]
+    if: contains(fromJSON('["pull_request"]'), github.event_name)
     runs-on: ubuntu-latest
     timeout-minutes: 5
-    if: contains(fromJSON('["pull_request"]'), github.event_name)
     steps:
-      - name: Checkout source code
-        uses: actions/checkout@v4
-
+      - uses: actions/checkout@v4
       - name: Check and delete comments
         run: |
           chmod +x ./.github/scripts/delete_pr_comments.sh
@@ -145,3 +117,20 @@ jobs:
             "${{ env.AWS_ENV_NAME }}" \
             "${{ github.event.pull_request.number }}" \
             "${{ secrets.GITHUB_TOKEN }}"
+
+  workflow-result-terraform-aws-management:
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+    needs: [terraform-aws-management]
+    if: always()
+    steps:
+      - name: Failure
+        if: >-
+          contains(needs.*.result, 'failure')
+          || contains(needs.*.result, 'cancelled')
+        run: |
+          echo "workflow failure"
+          exit 1
+      - name: Success
+        run: |
+          echo "workflow success"
